baseURL = "https://phanama.github.io/"
title = "YPhanama's Notes"
languageCode = "en-us"
theme = "ezhil"
disqusShortname = ""
googleAnalytics = "UA-142553815-1"
lastmod = [":fileModTime", ":default"]

copyright = "© 2020 Yudi A Phanama - CC-BY-SA 4.0 International"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 999
summaryLength = 20

enableGitInfo = true

[params]
    subtitle = "A Constant Learner"

    mainSections = ["notes"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]
    featherIconsCDN = false
    favicon = "images/Indonesiaball_with_kopiah.png"
    icon = "images/Indonesiaball_with_kopiah.png"
    mode = "light" # "dark", "light", "auto"

    customDarkCSS = "css/custom-dark.css"

    customJS = ["https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Notes"
url = "/notes"
weight = 2

[[menu.main]]
name = "Tech Stuff"
url = "/tech"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/phanama"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/yphanama"

# Enable tags.
[taxonomies]
   category = "categories"

